blank_issues_enabled: false
contact_links:
  - name: Questions and general discussions around bevy_mod_erased_component_registry
    url: https://github.com/AlexAegis/bevy_mod_erased_component_registry/discussions
    about: For general discussions, or questions please use discussions.
